/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AvisRouteImport } from './routes/avis'
import { Route as ComposantsRouteImport } from './routes/composants'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DemarrerRouteImport } from './routes/demarrer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as PlanDuSiteRouteImport } from './routes/plan-du-site'
import { Route as PubliciteRouteImport } from './routes/publicite'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as VerificationEmailRouteImport } from './routes/verification-email'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedDecouvrirRouteImport } from './routes/_authenticated/decouvrir'
import { Route as AuthenticatedMesAnnoncesRouteImport } from './routes/_authenticated/mes-annonces'
import { Route as AuthenticatedMesFormationsRouteImport } from './routes/_authenticated/mes-formations'
import { Route as AuthenticatedProfilRouteImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedTableauDeBordRouteImport } from './routes/_authenticated/tableau-de-bord'
import { Route as AnnuaireIndexRouteImport } from './routes/annuaire.index'
import { Route as AnnuaireSlugRouteImport } from './routes/annuaire.$slug'
import { Route as AnnuaireDepartementsRouteImport } from './routes/annuaire.departements'
import { Route as AnnuaireSoumettreRouteImport } from './routes/annuaire.soumettre'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FormationsIndexRouteImport } from './routes/formations.index'
import { Route as ForumIndexRouteImport } from './routes/forum.index'
import { Route as ForumTopicIdRouteImport } from './routes/forum.$topicId'
import { Route as LegalCguRouteImport } from './routes/legal.cgu'
import { Route as LegalCgvRouteImport } from './routes/legal.cgv'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal.confidentialite'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalMentionsLegalesRouteImport } from './routes/legal.mentions-legales'
import { Route as MarketplaceIndexRouteImport } from './routes/marketplace.index'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as MarketplacePublierRouteImport } from './routes/marketplace.publier'
import { Route as MembresIndexRouteImport } from './routes/membres.index'
import { Route as MembresMemberIdRouteImport } from './routes/membres.$memberId'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAbonnesRouteImport } from './routes/_authenticated/admin.abonnes'
import { Route as AuthenticatedAdminAnnuaireRouteImport } from './routes/_authenticated/admin.annuaire'
import { Route as AuthenticatedAdminConformiteRouteImport } from './routes/_authenticated/admin.conformite'
import { Route as AuthenticatedAdminContenusRouteImport } from './routes/_authenticated/admin.contenus'
import { Route as AuthenticatedAdminCrmRouteImport } from './routes/_authenticated/admin.crm'
import { Route as AuthenticatedAdminFormationsRouteImport } from './routes/_authenticated/admin.formations'
import { Route as AuthenticatedAdminForumRouteImport } from './routes/_authenticated/admin.forum'
import { Route as AuthenticatedAdminGeographieRouteImport } from './routes/_authenticated/admin.geographie'
import { Route as AuthenticatedAdminMarketplaceRouteImport } from './routes/_authenticated/admin.marketplace'
import { Route as AuthenticatedAdminMediathequeRouteImport } from './routes/_authenticated/admin.mediatheque'
import { Route as AuthenticatedAdminMessagesRouteImport } from './routes/_authenticated/admin.messages'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminModulesRouteImport } from './routes/_authenticated/admin.modules'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminPaiementsRouteImport } from './routes/_authenticated/admin.paiements'
import { Route as AuthenticatedAdminPilotageRouteImport } from './routes/_authenticated/admin.pilotage'
import { Route as AuthenticatedAdminRecettageRouteImport } from './routes/_authenticated/admin.recettage'
import { Route as AuthenticatedAdminRegieRouteImport } from './routes/_authenticated/admin.regie'
import { Route as AuthenticatedAdminSignalementsRouteImport } from './routes/_authenticated/admin.signalements'
import { Route as AuthenticatedAdminTemoignagesRouteImport } from './routes/_authenticated/admin.temoignages'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin.utilisateurs'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedCrmActionsRouteImport } from './routes/_authenticated/crm.actions'
import { Route as AuthenticatedCrmProspectsRouteImport } from './routes/_authenticated/crm.prospects'
import { Route as AuthenticatedMessagerieIndexRouteImport } from './routes/_authenticated/messagerie.index'
import { Route as AuthenticatedMessagerieConversationIdRouteImport } from './routes/_authenticated/messagerie.$conversationId'
import { Route as AnnuaireCategorieSlugRouteImport } from './routes/annuaire.categorie.$slug'
import { Route as AnnuaireDepartementSlugRouteImport } from './routes/annuaire.departement.$slug'
import { Route as FormationSlugIndexRouteImport } from './routes/formation.$slug.index'
import { Route as ForumCategorieSlugRouteImport } from './routes/forum.categorie.$slug'
import { Route as AuthenticatedCrmProspectProspectIdRouteImport } from './routes/_authenticated/crm.prospect.$prospectId'
import { Route as FormationSlugLeconLessonIdRouteImport } from './routes/formation.$slug.lecon.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisRoute = AvisRouteImport.update({
  id: '/avis',
  path: '/avis',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposantsRoute = ComposantsRouteImport.update({
  id: '/composants',
  path: '/composants',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemarrerRoute = DemarrerRouteImport.update({
  id: '/demarrer',
  path: '/demarrer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanDuSiteRoute = PlanDuSiteRouteImport.update({
  id: '/plan-du-site',
  path: '/plan-du-site',
  getParentRoute: () => rootRouteImport,
} as any)
const PubliciteRoute = PubliciteRouteImport.update({
  id: '/publicite',
  path: '/publicite',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationEmailRoute = VerificationEmailRouteImport.update({
  id: '/verification-email',
  path: '/verification-email',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecouvrirRoute = AuthenticatedDecouvrirRouteImport.update({
  id: '/decouvrir',
  path: '/decouvrir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMesAnnoncesRoute =
  AuthenticatedMesAnnoncesRouteImport.update({
    id: '/mes-annonces',
    path: '/mes-annonces',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesFormationsRoute =
  AuthenticatedMesFormationsRouteImport.update({
    id: '/mes-formations',
    path: '/mes-formations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfilRoute = AuthenticatedProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTableauDeBordRoute =
  AuthenticatedTableauDeBordRouteImport.update({
    id: '/tableau-de-bord',
    path: '/tableau-de-bord',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AnnuaireIndexRoute = AnnuaireIndexRouteImport.update({
  id: '/annuaire/',
  path: '/annuaire/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireSlugRoute = AnnuaireSlugRouteImport.update({
  id: '/annuaire/$slug',
  path: '/annuaire/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireDepartementsRoute = AnnuaireDepartementsRouteImport.update({
  id: '/annuaire/departements',
  path: '/annuaire/departements',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireSoumettreRoute = AnnuaireSoumettreRouteImport.update({
  id: '/annuaire/soumettre',
  path: '/annuaire/soumettre',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationsIndexRoute = FormationsIndexRouteImport.update({
  id: '/formations/',
  path: '/formations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumIndexRoute = ForumIndexRouteImport.update({
  id: '/forum/',
  path: '/forum/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumTopicIdRoute = ForumTopicIdRouteImport.update({
  id: '/forum/$topicId',
  path: '/forum/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCguRoute = LegalCguRouteImport.update({
  id: '/legal/cgu',
  path: '/legal/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCgvRoute = LegalCgvRouteImport.update({
  id: '/legal/cgv',
  path: '/legal/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/legal/confidentialite',
  path: '/legal/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsLegalesRoute = LegalMentionsLegalesRouteImport.update({
  id: '/legal/mentions-legales',
  path: '/legal/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceIndexRoute = MarketplaceIndexRouteImport.update({
  id: '/marketplace/',
  path: '/marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/marketplace/$slug',
  path: '/marketplace/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplacePublierRoute = MarketplacePublierRouteImport.update({
  id: '/marketplace/publier',
  path: '/marketplace/publier',
  getParentRoute: () => rootRouteImport,
} as any)
const MembresIndexRoute = MembresIndexRouteImport.update({
  id: '/membres/',
  path: '/membres/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembresMemberIdRoute = MembresMemberIdRouteImport.update({
  id: '/membres/$memberId',
  path: '/membres/$memberId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAbonnesRoute =
  AuthenticatedAdminAbonnesRouteImport.update({
    id: '/admin/abonnes',
    path: '/admin/abonnes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAnnuaireRoute =
  AuthenticatedAdminAnnuaireRouteImport.update({
    id: '/admin/annuaire',
    path: '/admin/annuaire',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminConformiteRoute =
  AuthenticatedAdminConformiteRouteImport.update({
    id: '/admin/conformite',
    path: '/admin/conformite',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminContenusRoute =
  AuthenticatedAdminContenusRouteImport.update({
    id: '/admin/contenus',
    path: '/admin/contenus',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCrmRoute = AuthenticatedAdminCrmRouteImport.update({
  id: '/admin/crm',
  path: '/admin/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminFormationsRoute =
  AuthenticatedAdminFormationsRouteImport.update({
    id: '/admin/formations',
    path: '/admin/formations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminForumRoute = AuthenticatedAdminForumRouteImport.update({
  id: '/admin/forum',
  path: '/admin/forum',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminGeographieRoute =
  AuthenticatedAdminGeographieRouteImport.update({
    id: '/admin/geographie',
    path: '/admin/geographie',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMarketplaceRoute =
  AuthenticatedAdminMarketplaceRouteImport.update({
    id: '/admin/marketplace',
    path: '/admin/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMediathequeRoute =
  AuthenticatedAdminMediathequeRouteImport.update({
    id: '/admin/mediatheque',
    path: '/admin/mediatheque',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMessagesRoute =
  AuthenticatedAdminMessagesRouteImport.update({
    id: '/admin/messages',
    path: '/admin/messages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/admin/moderation',
    path: '/admin/moderation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminModulesRoute =
  AuthenticatedAdminModulesRouteImport.update({
    id: '/admin/modules',
    path: '/admin/modules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPaiementsRoute =
  AuthenticatedAdminPaiementsRouteImport.update({
    id: '/admin/paiements',
    path: '/admin/paiements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPilotageRoute =
  AuthenticatedAdminPilotageRouteImport.update({
    id: '/admin/pilotage',
    path: '/admin/pilotage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRecettageRoute =
  AuthenticatedAdminRecettageRouteImport.update({
    id: '/admin/recettage',
    path: '/admin/recettage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRegieRoute = AuthenticatedAdminRegieRouteImport.update({
  id: '/admin/regie',
  path: '/admin/regie',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSignalementsRoute =
  AuthenticatedAdminSignalementsRouteImport.update({
    id: '/admin/signalements',
    path: '/admin/signalements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTemoignagesRoute =
  AuthenticatedAdminTemoignagesRouteImport.update({
    id: '/admin/temoignages',
    path: '/admin/temoignages',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/admin/utilisateurs',
    path: '/admin/utilisateurs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmActionsRoute = AuthenticatedCrmActionsRouteImport.update({
  id: '/crm/actions',
  path: '/crm/actions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmProspectsRoute =
  AuthenticatedCrmProspectsRouteImport.update({
    id: '/crm/prospects',
    path: '/crm/prospects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagerieIndexRoute =
  AuthenticatedMessagerieIndexRouteImport.update({
    id: '/messagerie/',
    path: '/messagerie/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagerieConversationIdRoute =
  AuthenticatedMessagerieConversationIdRouteImport.update({
    id: '/messagerie/$conversationId',
    path: '/messagerie/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AnnuaireCategorieSlugRoute = AnnuaireCategorieSlugRouteImport.update({
  id: '/annuaire/categorie/$slug',
  path: '/annuaire/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnuaireDepartementSlugRoute = AnnuaireDepartementSlugRouteImport.update({
  id: '/annuaire/departement/$slug',
  path: '/annuaire/departement/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationSlugIndexRoute = FormationSlugIndexRouteImport.update({
  id: '/formation/$slug/',
  path: '/formation/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumCategorieSlugRoute = ForumCategorieSlugRouteImport.update({
  id: '/forum/categorie/$slug',
  path: '/forum/categorie/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmProspectProspectIdRoute =
  AuthenticatedCrmProspectProspectIdRouteImport.update({
    id: '/crm/prospect/$prospectId',
    path: '/crm/prospect/$prospectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const FormationSlugLeconLessonIdRoute =
  FormationSlugLeconLessonIdRouteImport.update({
    id: '/formation/$slug/lecon/$lessonId',
    path: '/formation/$slug/lecon/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/composants': typeof ComposantsRoute
  '/contact': typeof ContactRoute
  '/demarrer': typeof DemarrerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/mcp': typeof McpRoute
  '/merci': typeof MerciRoute
  '/plan-du-site': typeof PlanDuSiteRoute
  '/publicite': typeof PubliciteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/temoignages': typeof TemoignagesRoute
  '/verification-email': typeof VerificationEmailRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/decouvrir': typeof AuthenticatedDecouvrirRoute
  '/mes-annonces': typeof AuthenticatedMesAnnoncesRoute
  '/mes-formations': typeof AuthenticatedMesFormationsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/annuaire/$slug': typeof AnnuaireSlugRoute
  '/annuaire/departements': typeof AnnuaireDepartementsRoute
  '/annuaire/soumettre': typeof AnnuaireSoumettreRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/marketplace/publier': typeof MarketplacePublierRoute
  '/membres/$memberId': typeof MembresMemberIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/annuaire/': typeof AnnuaireIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/formations/': typeof FormationsIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/membres/': typeof MembresIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/abonnes': typeof AuthenticatedAdminAbonnesRoute
  '/admin/annuaire': typeof AuthenticatedAdminAnnuaireRoute
  '/admin/conformite': typeof AuthenticatedAdminConformiteRoute
  '/admin/contenus': typeof AuthenticatedAdminContenusRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/formations': typeof AuthenticatedAdminFormationsRoute
  '/admin/forum': typeof AuthenticatedAdminForumRoute
  '/admin/geographie': typeof AuthenticatedAdminGeographieRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/mediatheque': typeof AuthenticatedAdminMediathequeRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/pilotage': typeof AuthenticatedAdminPilotageRoute
  '/admin/recettage': typeof AuthenticatedAdminRecettageRoute
  '/admin/regie': typeof AuthenticatedAdminRegieRoute
  '/admin/signalements': typeof AuthenticatedAdminSignalementsRoute
  '/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/crm/actions': typeof AuthenticatedCrmActionsRoute
  '/crm/prospects': typeof AuthenticatedCrmProspectsRoute
  '/messagerie/$conversationId': typeof AuthenticatedMessagerieConversationIdRoute
  '/annuaire/categorie/$slug': typeof AnnuaireCategorieSlugRoute
  '/annuaire/departement/$slug': typeof AnnuaireDepartementSlugRoute
  '/forum/categorie/$slug': typeof ForumCategorieSlugRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/messagerie/': typeof AuthenticatedMessagerieIndexRoute
  '/formation/$slug/': typeof FormationSlugIndexRoute
  '/crm/prospect/$prospectId': typeof AuthenticatedCrmProspectProspectIdRoute
  '/formation/$slug/lecon/$lessonId': typeof FormationSlugLeconLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/composants': typeof ComposantsRoute
  '/contact': typeof ContactRoute
  '/demarrer': typeof DemarrerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/mcp': typeof McpRoute
  '/merci': typeof MerciRoute
  '/plan-du-site': typeof PlanDuSiteRoute
  '/publicite': typeof PubliciteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/temoignages': typeof TemoignagesRoute
  '/verification-email': typeof VerificationEmailRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/decouvrir': typeof AuthenticatedDecouvrirRoute
  '/mes-annonces': typeof AuthenticatedMesAnnoncesRoute
  '/mes-formations': typeof AuthenticatedMesFormationsRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/annuaire/$slug': typeof AnnuaireSlugRoute
  '/annuaire/departements': typeof AnnuaireDepartementsRoute
  '/annuaire/soumettre': typeof AnnuaireSoumettreRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/marketplace/publier': typeof MarketplacePublierRoute
  '/membres/$memberId': typeof MembresMemberIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/annuaire': typeof AnnuaireIndexRoute
  '/blog': typeof BlogIndexRoute
  '/formations': typeof FormationsIndexRoute
  '/forum': typeof ForumIndexRoute
  '/marketplace': typeof MarketplaceIndexRoute
  '/membres': typeof MembresIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/abonnes': typeof AuthenticatedAdminAbonnesRoute
  '/admin/annuaire': typeof AuthenticatedAdminAnnuaireRoute
  '/admin/conformite': typeof AuthenticatedAdminConformiteRoute
  '/admin/contenus': typeof AuthenticatedAdminContenusRoute
  '/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/admin/formations': typeof AuthenticatedAdminFormationsRoute
  '/admin/forum': typeof AuthenticatedAdminForumRoute
  '/admin/geographie': typeof AuthenticatedAdminGeographieRoute
  '/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/admin/mediatheque': typeof AuthenticatedAdminMediathequeRoute
  '/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/pilotage': typeof AuthenticatedAdminPilotageRoute
  '/admin/recettage': typeof AuthenticatedAdminRecettageRoute
  '/admin/regie': typeof AuthenticatedAdminRegieRoute
  '/admin/signalements': typeof AuthenticatedAdminSignalementsRoute
  '/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/crm/actions': typeof AuthenticatedCrmActionsRoute
  '/crm/prospects': typeof AuthenticatedCrmProspectsRoute
  '/messagerie/$conversationId': typeof AuthenticatedMessagerieConversationIdRoute
  '/annuaire/categorie/$slug': typeof AnnuaireCategorieSlugRoute
  '/annuaire/departement/$slug': typeof AnnuaireDepartementSlugRoute
  '/forum/categorie/$slug': typeof ForumCategorieSlugRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/messagerie': typeof AuthenticatedMessagerieIndexRoute
  '/formation/$slug': typeof FormationSlugIndexRoute
  '/crm/prospect/$prospectId': typeof AuthenticatedCrmProspectProspectIdRoute
  '/formation/$slug/lecon/$lessonId': typeof FormationSlugLeconLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/avis': typeof AvisRoute
  '/composants': typeof ComposantsRoute
  '/contact': typeof ContactRoute
  '/demarrer': typeof DemarrerRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/maintenance': typeof MaintenanceRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/mcp': typeof McpRoute
  '/merci': typeof MerciRoute
  '/plan-du-site': typeof PlanDuSiteRoute
  '/publicite': typeof PubliciteRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/temoignages': typeof TemoignagesRoute
  '/verification-email': typeof VerificationEmailRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/_authenticated/decouvrir': typeof AuthenticatedDecouvrirRoute
  '/_authenticated/mes-annonces': typeof AuthenticatedMesAnnoncesRoute
  '/_authenticated/mes-formations': typeof AuthenticatedMesFormationsRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/_authenticated/tableau-de-bord': typeof AuthenticatedTableauDeBordRoute
  '/annuaire/$slug': typeof AnnuaireSlugRoute
  '/annuaire/departements': typeof AnnuaireDepartementsRoute
  '/annuaire/soumettre': typeof AnnuaireSoumettreRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/forum/$topicId': typeof ForumTopicIdRoute
  '/legal/cgu': typeof LegalCguRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions-legales': typeof LegalMentionsLegalesRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/marketplace/publier': typeof MarketplacePublierRoute
  '/membres/$memberId': typeof MembresMemberIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/annuaire/': typeof AnnuaireIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/formations/': typeof FormationsIndexRoute
  '/forum/': typeof ForumIndexRoute
  '/marketplace/': typeof MarketplaceIndexRoute
  '/membres/': typeof MembresIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/admin/abonnes': typeof AuthenticatedAdminAbonnesRoute
  '/_authenticated/admin/annuaire': typeof AuthenticatedAdminAnnuaireRoute
  '/_authenticated/admin/conformite': typeof AuthenticatedAdminConformiteRoute
  '/_authenticated/admin/contenus': typeof AuthenticatedAdminContenusRoute
  '/_authenticated/admin/crm': typeof AuthenticatedAdminCrmRoute
  '/_authenticated/admin/formations': typeof AuthenticatedAdminFormationsRoute
  '/_authenticated/admin/forum': typeof AuthenticatedAdminForumRoute
  '/_authenticated/admin/geographie': typeof AuthenticatedAdminGeographieRoute
  '/_authenticated/admin/marketplace': typeof AuthenticatedAdminMarketplaceRoute
  '/_authenticated/admin/mediatheque': typeof AuthenticatedAdminMediathequeRoute
  '/_authenticated/admin/messages': typeof AuthenticatedAdminMessagesRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/_authenticated/admin/pilotage': typeof AuthenticatedAdminPilotageRoute
  '/_authenticated/admin/recettage': typeof AuthenticatedAdminRecettageRoute
  '/_authenticated/admin/regie': typeof AuthenticatedAdminRegieRoute
  '/_authenticated/admin/signalements': typeof AuthenticatedAdminSignalementsRoute
  '/_authenticated/admin/temoignages': typeof AuthenticatedAdminTemoignagesRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/crm/actions': typeof AuthenticatedCrmActionsRoute
  '/_authenticated/crm/prospects': typeof AuthenticatedCrmProspectsRoute
  '/_authenticated/messagerie/$conversationId': typeof AuthenticatedMessagerieConversationIdRoute
  '/annuaire/categorie/$slug': typeof AnnuaireCategorieSlugRoute
  '/annuaire/departement/$slug': typeof AnnuaireDepartementSlugRoute
  '/forum/categorie/$slug': typeof ForumCategorieSlugRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/messagerie/': typeof AuthenticatedMessagerieIndexRoute
  '/formation/$slug/': typeof FormationSlugIndexRoute
  '/_authenticated/crm/prospect/$prospectId': typeof AuthenticatedCrmProspectProspectIdRoute
  '/formation/$slug/lecon/$lessonId': typeof FormationSlugLeconLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/avis'
    | '/composants'
    | '/contact'
    | '/demarrer'
    | '/faq'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/maintenance'
    | '/manifest.webmanifest'
    | '/mcp'
    | '/merci'
    | '/plan-du-site'
    | '/publicite'
    | '/reset-password'
    | '/robots.txt'
    | '/rss.xml'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/temoignages'
    | '/verification-email'
    | '/.well-known/oauth-protected-resource'
    | '/compte'
    | '/decouvrir'
    | '/mes-annonces'
    | '/mes-formations'
    | '/profil'
    | '/tableau-de-bord'
    | '/annuaire/$slug'
    | '/annuaire/departements'
    | '/annuaire/soumettre'
    | '/api/stripe-webhook'
    | '/blog/$slug'
    | '/forum/$topicId'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/marketplace/$slug'
    | '/marketplace/publier'
    | '/membres/$memberId'
    | '/pages/$slug'
    | '/annuaire/'
    | '/blog/'
    | '/formations/'
    | '/forum/'
    | '/marketplace/'
    | '/membres/'
    | '/.lovable/oauth/consent'
    | '/admin/abonnes'
    | '/admin/annuaire'
    | '/admin/conformite'
    | '/admin/contenus'
    | '/admin/crm'
    | '/admin/formations'
    | '/admin/forum'
    | '/admin/geographie'
    | '/admin/marketplace'
    | '/admin/mediatheque'
    | '/admin/messages'
    | '/admin/moderation'
    | '/admin/modules'
    | '/admin/pages'
    | '/admin/paiements'
    | '/admin/pilotage'
    | '/admin/recettage'
    | '/admin/regie'
    | '/admin/signalements'
    | '/admin/temoignages'
    | '/admin/utilisateurs'
    | '/crm/actions'
    | '/crm/prospects'
    | '/messagerie/$conversationId'
    | '/annuaire/categorie/$slug'
    | '/annuaire/departement/$slug'
    | '/forum/categorie/$slug'
    | '/admin/'
    | '/crm/'
    | '/messagerie/'
    | '/formation/$slug/'
    | '/crm/prospect/$prospectId'
    | '/formation/$slug/lecon/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/avis'
    | '/composants'
    | '/contact'
    | '/demarrer'
    | '/faq'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/maintenance'
    | '/manifest.webmanifest'
    | '/mcp'
    | '/merci'
    | '/plan-du-site'
    | '/publicite'
    | '/reset-password'
    | '/robots.txt'
    | '/rss.xml'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/temoignages'
    | '/verification-email'
    | '/.well-known/oauth-protected-resource'
    | '/compte'
    | '/decouvrir'
    | '/mes-annonces'
    | '/mes-formations'
    | '/profil'
    | '/tableau-de-bord'
    | '/annuaire/$slug'
    | '/annuaire/departements'
    | '/annuaire/soumettre'
    | '/api/stripe-webhook'
    | '/blog/$slug'
    | '/forum/$topicId'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/marketplace/$slug'
    | '/marketplace/publier'
    | '/membres/$memberId'
    | '/pages/$slug'
    | '/annuaire'
    | '/blog'
    | '/formations'
    | '/forum'
    | '/marketplace'
    | '/membres'
    | '/.lovable/oauth/consent'
    | '/admin/abonnes'
    | '/admin/annuaire'
    | '/admin/conformite'
    | '/admin/contenus'
    | '/admin/crm'
    | '/admin/formations'
    | '/admin/forum'
    | '/admin/geographie'
    | '/admin/marketplace'
    | '/admin/mediatheque'
    | '/admin/messages'
    | '/admin/moderation'
    | '/admin/modules'
    | '/admin/pages'
    | '/admin/paiements'
    | '/admin/pilotage'
    | '/admin/recettage'
    | '/admin/regie'
    | '/admin/signalements'
    | '/admin/temoignages'
    | '/admin/utilisateurs'
    | '/crm/actions'
    | '/crm/prospects'
    | '/messagerie/$conversationId'
    | '/annuaire/categorie/$slug'
    | '/annuaire/departement/$slug'
    | '/forum/categorie/$slug'
    | '/admin'
    | '/crm'
    | '/messagerie'
    | '/formation/$slug'
    | '/crm/prospect/$prospectId'
    | '/formation/$slug/lecon/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/a-propos'
    | '/avis'
    | '/composants'
    | '/contact'
    | '/demarrer'
    | '/faq'
    | '/forgot-password'
    | '/guide'
    | '/login'
    | '/maintenance'
    | '/manifest.webmanifest'
    | '/mcp'
    | '/merci'
    | '/plan-du-site'
    | '/publicite'
    | '/reset-password'
    | '/robots.txt'
    | '/rss.xml'
    | '/signup'
    | '/sitemap.xml'
    | '/tarifs'
    | '/temoignages'
    | '/verification-email'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/compte'
    | '/_authenticated/decouvrir'
    | '/_authenticated/mes-annonces'
    | '/_authenticated/mes-formations'
    | '/_authenticated/profil'
    | '/_authenticated/tableau-de-bord'
    | '/annuaire/$slug'
    | '/annuaire/departements'
    | '/annuaire/soumettre'
    | '/api/stripe-webhook'
    | '/blog/$slug'
    | '/forum/$topicId'
    | '/legal/cgu'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions-legales'
    | '/marketplace/$slug'
    | '/marketplace/publier'
    | '/membres/$memberId'
    | '/pages/$slug'
    | '/annuaire/'
    | '/blog/'
    | '/formations/'
    | '/forum/'
    | '/marketplace/'
    | '/membres/'
    | '/.lovable/oauth/consent'
    | '/_authenticated/admin/abonnes'
    | '/_authenticated/admin/annuaire'
    | '/_authenticated/admin/conformite'
    | '/_authenticated/admin/contenus'
    | '/_authenticated/admin/crm'
    | '/_authenticated/admin/formations'
    | '/_authenticated/admin/forum'
    | '/_authenticated/admin/geographie'
    | '/_authenticated/admin/marketplace'
    | '/_authenticated/admin/mediatheque'
    | '/_authenticated/admin/messages'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/modules'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/paiements'
    | '/_authenticated/admin/pilotage'
    | '/_authenticated/admin/recettage'
    | '/_authenticated/admin/regie'
    | '/_authenticated/admin/signalements'
    | '/_authenticated/admin/temoignages'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/crm/actions'
    | '/_authenticated/crm/prospects'
    | '/_authenticated/messagerie/$conversationId'
    | '/annuaire/categorie/$slug'
    | '/annuaire/departement/$slug'
    | '/forum/categorie/$slug'
    | '/_authenticated/admin/'
    | '/_authenticated/crm/'
    | '/_authenticated/messagerie/'
    | '/formation/$slug/'
    | '/_authenticated/crm/prospect/$prospectId'
    | '/formation/$slug/lecon/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AProposRoute: typeof AProposRoute
  AvisRoute: typeof AvisRoute
  ComposantsRoute: typeof ComposantsRoute
  ContactRoute: typeof ContactRoute
  DemarrerRoute: typeof DemarrerRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  MaintenanceRoute: typeof MaintenanceRoute
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  McpRoute: typeof McpRoute
  MerciRoute: typeof MerciRoute
  PlanDuSiteRoute: typeof PlanDuSiteRoute
  PubliciteRoute: typeof PubliciteRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  TemoignagesRoute: typeof TemoignagesRoute
  VerificationEmailRoute: typeof VerificationEmailRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AnnuaireSlugRoute: typeof AnnuaireSlugRoute
  AnnuaireDepartementsRoute: typeof AnnuaireDepartementsRoute
  AnnuaireSoumettreRoute: typeof AnnuaireSoumettreRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ForumTopicIdRoute: typeof ForumTopicIdRoute
  LegalCguRoute: typeof LegalCguRoute
  LegalCgvRoute: typeof LegalCgvRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalMentionsLegalesRoute: typeof LegalMentionsLegalesRoute
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
  MarketplacePublierRoute: typeof MarketplacePublierRoute
  MembresMemberIdRoute: typeof MembresMemberIdRoute
  PagesSlugRoute: typeof PagesSlugRoute
  AnnuaireIndexRoute: typeof AnnuaireIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FormationsIndexRoute: typeof FormationsIndexRoute
  ForumIndexRoute: typeof ForumIndexRoute
  MarketplaceIndexRoute: typeof MarketplaceIndexRoute
  MembresIndexRoute: typeof MembresIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  AnnuaireCategorieSlugRoute: typeof AnnuaireCategorieSlugRoute
  AnnuaireDepartementSlugRoute: typeof AnnuaireDepartementSlugRoute
  ForumCategorieSlugRoute: typeof ForumCategorieSlugRoute
  FormationSlugIndexRoute: typeof FormationSlugIndexRoute
  FormationSlugLeconLessonIdRoute: typeof FormationSlugLeconLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avis': {
      id: '/avis'
      path: '/avis'
      fullPath: '/avis'
      preLoaderRoute: typeof AvisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/composants': {
      id: '/composants'
      path: '/composants'
      fullPath: '/composants'
      preLoaderRoute: typeof ComposantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demarrer': {
      id: '/demarrer'
      path: '/demarrer'
      fullPath: '/demarrer'
      preLoaderRoute: typeof DemarrerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-du-site': {
      id: '/plan-du-site'
      path: '/plan-du-site'
      fullPath: '/plan-du-site'
      preLoaderRoute: typeof PlanDuSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicite': {
      id: '/publicite'
      path: '/publicite'
      fullPath: '/publicite'
      preLoaderRoute: typeof PubliciteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification-email': {
      id: '/verification-email'
      path: '/verification-email'
      fullPath: '/verification-email'
      preLoaderRoute: typeof VerificationEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decouvrir': {
      id: '/_authenticated/decouvrir'
      path: '/decouvrir'
      fullPath: '/decouvrir'
      preLoaderRoute: typeof AuthenticatedDecouvrirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-annonces': {
      id: '/_authenticated/mes-annonces'
      path: '/mes-annonces'
      fullPath: '/mes-annonces'
      preLoaderRoute: typeof AuthenticatedMesAnnoncesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes-formations': {
      id: '/_authenticated/mes-formations'
      path: '/mes-formations'
      fullPath: '/mes-formations'
      preLoaderRoute: typeof AuthenticatedMesFormationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tableau-de-bord': {
      id: '/_authenticated/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof AuthenticatedTableauDeBordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/annuaire/': {
      id: '/annuaire/'
      path: '/annuaire'
      fullPath: '/annuaire/'
      preLoaderRoute: typeof AnnuaireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire/$slug': {
      id: '/annuaire/$slug'
      path: '/annuaire/$slug'
      fullPath: '/annuaire/$slug'
      preLoaderRoute: typeof AnnuaireSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire/departements': {
      id: '/annuaire/departements'
      path: '/annuaire/departements'
      fullPath: '/annuaire/departements'
      preLoaderRoute: typeof AnnuaireDepartementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire/soumettre': {
      id: '/annuaire/soumettre'
      path: '/annuaire/soumettre'
      fullPath: '/annuaire/soumettre'
      preLoaderRoute: typeof AnnuaireSoumettreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formations/': {
      id: '/formations/'
      path: '/formations'
      fullPath: '/formations/'
      preLoaderRoute: typeof FormationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/': {
      id: '/forum/'
      path: '/forum'
      fullPath: '/forum/'
      preLoaderRoute: typeof ForumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/$topicId': {
      id: '/forum/$topicId'
      path: '/forum/$topicId'
      fullPath: '/forum/$topicId'
      preLoaderRoute: typeof ForumTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgu': {
      id: '/legal/cgu'
      path: '/legal/cgu'
      fullPath: '/legal/cgu'
      preLoaderRoute: typeof LegalCguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgv': {
      id: '/legal/cgv'
      path: '/legal/cgv'
      fullPath: '/legal/cgv'
      preLoaderRoute: typeof LegalCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/legal/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions-legales': {
      id: '/legal/mentions-legales'
      path: '/legal/mentions-legales'
      fullPath: '/legal/mentions-legales'
      preLoaderRoute: typeof LegalMentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/': {
      id: '/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof MarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/marketplace/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/publier': {
      id: '/marketplace/publier'
      path: '/marketplace/publier'
      fullPath: '/marketplace/publier'
      preLoaderRoute: typeof MarketplacePublierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membres/': {
      id: '/membres/'
      path: '/membres'
      fullPath: '/membres/'
      preLoaderRoute: typeof MembresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membres/$memberId': {
      id: '/membres/$memberId'
      path: '/membres/$memberId'
      fullPath: '/membres/$memberId'
      preLoaderRoute: typeof MembresMemberIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/abonnes': {
      id: '/_authenticated/admin/abonnes'
      path: '/admin/abonnes'
      fullPath: '/admin/abonnes'
      preLoaderRoute: typeof AuthenticatedAdminAbonnesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/annuaire': {
      id: '/_authenticated/admin/annuaire'
      path: '/admin/annuaire'
      fullPath: '/admin/annuaire'
      preLoaderRoute: typeof AuthenticatedAdminAnnuaireRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/conformite': {
      id: '/_authenticated/admin/conformite'
      path: '/admin/conformite'
      fullPath: '/admin/conformite'
      preLoaderRoute: typeof AuthenticatedAdminConformiteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/contenus': {
      id: '/_authenticated/admin/contenus'
      path: '/admin/contenus'
      fullPath: '/admin/contenus'
      preLoaderRoute: typeof AuthenticatedAdminContenusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/crm': {
      id: '/_authenticated/admin/crm'
      path: '/admin/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AuthenticatedAdminCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/formations': {
      id: '/_authenticated/admin/formations'
      path: '/admin/formations'
      fullPath: '/admin/formations'
      preLoaderRoute: typeof AuthenticatedAdminFormationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/forum': {
      id: '/_authenticated/admin/forum'
      path: '/admin/forum'
      fullPath: '/admin/forum'
      preLoaderRoute: typeof AuthenticatedAdminForumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/geographie': {
      id: '/_authenticated/admin/geographie'
      path: '/admin/geographie'
      fullPath: '/admin/geographie'
      preLoaderRoute: typeof AuthenticatedAdminGeographieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/marketplace': {
      id: '/_authenticated/admin/marketplace'
      path: '/admin/marketplace'
      fullPath: '/admin/marketplace'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mediatheque': {
      id: '/_authenticated/admin/mediatheque'
      path: '/admin/mediatheque'
      fullPath: '/admin/mediatheque'
      preLoaderRoute: typeof AuthenticatedAdminMediathequeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/messages': {
      id: '/_authenticated/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AuthenticatedAdminMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/modules': {
      id: '/_authenticated/admin/modules'
      path: '/admin/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AuthenticatedAdminModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/paiements': {
      id: '/_authenticated/admin/paiements'
      path: '/admin/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AuthenticatedAdminPaiementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/pilotage': {
      id: '/_authenticated/admin/pilotage'
      path: '/admin/pilotage'
      fullPath: '/admin/pilotage'
      preLoaderRoute: typeof AuthenticatedAdminPilotageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/recettage': {
      id: '/_authenticated/admin/recettage'
      path: '/admin/recettage'
      fullPath: '/admin/recettage'
      preLoaderRoute: typeof AuthenticatedAdminRecettageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/regie': {
      id: '/_authenticated/admin/regie'
      path: '/admin/regie'
      fullPath: '/admin/regie'
      preLoaderRoute: typeof AuthenticatedAdminRegieRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/signalements': {
      id: '/_authenticated/admin/signalements'
      path: '/admin/signalements'
      fullPath: '/admin/signalements'
      preLoaderRoute: typeof AuthenticatedAdminSignalementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/temoignages': {
      id: '/_authenticated/admin/temoignages'
      path: '/admin/temoignages'
      fullPath: '/admin/temoignages'
      preLoaderRoute: typeof AuthenticatedAdminTemoignagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/admin/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/actions': {
      id: '/_authenticated/crm/actions'
      path: '/crm/actions'
      fullPath: '/crm/actions'
      preLoaderRoute: typeof AuthenticatedCrmActionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm/prospects': {
      id: '/_authenticated/crm/prospects'
      path: '/crm/prospects'
      fullPath: '/crm/prospects'
      preLoaderRoute: typeof AuthenticatedCrmProspectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messagerie/': {
      id: '/_authenticated/messagerie/'
      path: '/messagerie'
      fullPath: '/messagerie/'
      preLoaderRoute: typeof AuthenticatedMessagerieIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messagerie/$conversationId': {
      id: '/_authenticated/messagerie/$conversationId'
      path: '/messagerie/$conversationId'
      fullPath: '/messagerie/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagerieConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/annuaire/categorie/$slug': {
      id: '/annuaire/categorie/$slug'
      path: '/annuaire/categorie/$slug'
      fullPath: '/annuaire/categorie/$slug'
      preLoaderRoute: typeof AnnuaireCategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuaire/departement/$slug': {
      id: '/annuaire/departement/$slug'
      path: '/annuaire/departement/$slug'
      fullPath: '/annuaire/departement/$slug'
      preLoaderRoute: typeof AnnuaireDepartementSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation/$slug/': {
      id: '/formation/$slug/'
      path: '/formation/$slug'
      fullPath: '/formation/$slug/'
      preLoaderRoute: typeof FormationSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum/categorie/$slug': {
      id: '/forum/categorie/$slug'
      path: '/forum/categorie/$slug'
      fullPath: '/forum/categorie/$slug'
      preLoaderRoute: typeof ForumCategorieSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm/prospect/$prospectId': {
      id: '/_authenticated/crm/prospect/$prospectId'
      path: '/crm/prospect/$prospectId'
      fullPath: '/crm/prospect/$prospectId'
      preLoaderRoute: typeof AuthenticatedCrmProspectProspectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/formation/$slug/lecon/$lessonId': {
      id: '/formation/$slug/lecon/$lessonId'
      path: '/formation/$slug/lecon/$lessonId'
      fullPath: '/formation/$slug/lecon/$lessonId'
      preLoaderRoute: typeof FormationSlugLeconLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
  AuthenticatedDecouvrirRoute: typeof AuthenticatedDecouvrirRoute
  AuthenticatedMesAnnoncesRoute: typeof AuthenticatedMesAnnoncesRoute
  AuthenticatedMesFormationsRoute: typeof AuthenticatedMesFormationsRoute
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedTableauDeBordRoute: typeof AuthenticatedTableauDeBordRoute
  AuthenticatedAdminAbonnesRoute: typeof AuthenticatedAdminAbonnesRoute
  AuthenticatedAdminAnnuaireRoute: typeof AuthenticatedAdminAnnuaireRoute
  AuthenticatedAdminConformiteRoute: typeof AuthenticatedAdminConformiteRoute
  AuthenticatedAdminContenusRoute: typeof AuthenticatedAdminContenusRoute
  AuthenticatedAdminCrmRoute: typeof AuthenticatedAdminCrmRoute
  AuthenticatedAdminFormationsRoute: typeof AuthenticatedAdminFormationsRoute
  AuthenticatedAdminForumRoute: typeof AuthenticatedAdminForumRoute
  AuthenticatedAdminGeographieRoute: typeof AuthenticatedAdminGeographieRoute
  AuthenticatedAdminMarketplaceRoute: typeof AuthenticatedAdminMarketplaceRoute
  AuthenticatedAdminMediathequeRoute: typeof AuthenticatedAdminMediathequeRoute
  AuthenticatedAdminMessagesRoute: typeof AuthenticatedAdminMessagesRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminModulesRoute: typeof AuthenticatedAdminModulesRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPaiementsRoute: typeof AuthenticatedAdminPaiementsRoute
  AuthenticatedAdminPilotageRoute: typeof AuthenticatedAdminPilotageRoute
  AuthenticatedAdminRecettageRoute: typeof AuthenticatedAdminRecettageRoute
  AuthenticatedAdminRegieRoute: typeof AuthenticatedAdminRegieRoute
  AuthenticatedAdminSignalementsRoute: typeof AuthenticatedAdminSignalementsRoute
  AuthenticatedAdminTemoignagesRoute: typeof AuthenticatedAdminTemoignagesRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedCrmActionsRoute: typeof AuthenticatedCrmActionsRoute
  AuthenticatedCrmProspectsRoute: typeof AuthenticatedCrmProspectsRoute
  AuthenticatedMessagerieConversationIdRoute: typeof AuthenticatedMessagerieConversationIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedMessagerieIndexRoute: typeof AuthenticatedMessagerieIndexRoute
  AuthenticatedCrmProspectProspectIdRoute: typeof AuthenticatedCrmProspectProspectIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
  AuthenticatedDecouvrirRoute: AuthenticatedDecouvrirRoute,
  AuthenticatedMesAnnoncesRoute: AuthenticatedMesAnnoncesRoute,
  AuthenticatedMesFormationsRoute: AuthenticatedMesFormationsRoute,
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedTableauDeBordRoute: AuthenticatedTableauDeBordRoute,
  AuthenticatedAdminAbonnesRoute: AuthenticatedAdminAbonnesRoute,
  AuthenticatedAdminAnnuaireRoute: AuthenticatedAdminAnnuaireRoute,
  AuthenticatedAdminConformiteRoute: AuthenticatedAdminConformiteRoute,
  AuthenticatedAdminContenusRoute: AuthenticatedAdminContenusRoute,
  AuthenticatedAdminCrmRoute: AuthenticatedAdminCrmRoute,
  AuthenticatedAdminFormationsRoute: AuthenticatedAdminFormationsRoute,
  AuthenticatedAdminForumRoute: AuthenticatedAdminForumRoute,
  AuthenticatedAdminGeographieRoute: AuthenticatedAdminGeographieRoute,
  AuthenticatedAdminMarketplaceRoute: AuthenticatedAdminMarketplaceRoute,
  AuthenticatedAdminMediathequeRoute: AuthenticatedAdminMediathequeRoute,
  AuthenticatedAdminMessagesRoute: AuthenticatedAdminMessagesRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminModulesRoute: AuthenticatedAdminModulesRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminPaiementsRoute: AuthenticatedAdminPaiementsRoute,
  AuthenticatedAdminPilotageRoute: AuthenticatedAdminPilotageRoute,
  AuthenticatedAdminRecettageRoute: AuthenticatedAdminRecettageRoute,
  AuthenticatedAdminRegieRoute: AuthenticatedAdminRegieRoute,
  AuthenticatedAdminSignalementsRoute: AuthenticatedAdminSignalementsRoute,
  AuthenticatedAdminTemoignagesRoute: AuthenticatedAdminTemoignagesRoute,
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
  AuthenticatedCrmActionsRoute: AuthenticatedCrmActionsRoute,
  AuthenticatedCrmProspectsRoute: AuthenticatedCrmProspectsRoute,
  AuthenticatedMessagerieConversationIdRoute:
    AuthenticatedMessagerieConversationIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedMessagerieIndexRoute: AuthenticatedMessagerieIndexRoute,
  AuthenticatedCrmProspectProspectIdRoute:
    AuthenticatedCrmProspectProspectIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AProposRoute: AProposRoute,
  AvisRoute: AvisRoute,
  ComposantsRoute: ComposantsRoute,
  ContactRoute: ContactRoute,
  DemarrerRoute: DemarrerRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  MaintenanceRoute: MaintenanceRoute,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  McpRoute: McpRoute,
  MerciRoute: MerciRoute,
  PlanDuSiteRoute: PlanDuSiteRoute,
  PubliciteRoute: PubliciteRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  TemoignagesRoute: TemoignagesRoute,
  VerificationEmailRoute: VerificationEmailRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AnnuaireSlugRoute: AnnuaireSlugRoute,
  AnnuaireDepartementsRoute: AnnuaireDepartementsRoute,
  AnnuaireSoumettreRoute: AnnuaireSoumettreRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  BlogSlugRoute: BlogSlugRoute,
  ForumTopicIdRoute: ForumTopicIdRoute,
  LegalCguRoute: LegalCguRoute,
  LegalCgvRoute: LegalCgvRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalMentionsLegalesRoute: LegalMentionsLegalesRoute,
  MarketplaceSlugRoute: MarketplaceSlugRoute,
  MarketplacePublierRoute: MarketplacePublierRoute,
  MembresMemberIdRoute: MembresMemberIdRoute,
  PagesSlugRoute: PagesSlugRoute,
  AnnuaireIndexRoute: AnnuaireIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  FormationsIndexRoute: FormationsIndexRoute,
  ForumIndexRoute: ForumIndexRoute,
  MarketplaceIndexRoute: MarketplaceIndexRoute,
  MembresIndexRoute: MembresIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  AnnuaireCategorieSlugRoute: AnnuaireCategorieSlugRoute,
  AnnuaireDepartementSlugRoute: AnnuaireDepartementSlugRoute,
  ForumCategorieSlugRoute: ForumCategorieSlugRoute,
  FormationSlugIndexRoute: FormationSlugIndexRoute,
  FormationSlugLeconLessonIdRoute: FormationSlugLeconLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
